# Generated by Django 5.2.7 on 2025-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('developer', models.CharField(blank=True, max_length=255)),
                ('icon_url', models.URLField(blank=True)),
                ('playstore_url', models.URLField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_synced', 'title'],
            },
        ),
    ]
