# Generated by Django 5.2.7 on 2025-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_learning_project_learningstage_projectstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.PositiveIntegerField(help_text='Percentage 0-100')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
