# Generated by Django 5.2.7 on 2025-10-16 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_adpublisherid_appprivacypolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appprivacypolicy',
            old_name='content',
            new_name='intro_text',
        ),
        migrations.AddField(
            model_name='appprivacypolicy',
            name='contact_email',
            field=models.EmailField(default='novera.labs1@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='appprivacypolicy',
            name='footer_note',
            field=models.TextField(default='This Privacy Policy applies only to this app.'),
        ),
        migrations.AddField(
            model_name='appprivacypolicy',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appprivacypolicy',
            name='app_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PolicyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='home.appprivacypolicy')),
            ],
        ),
    ]
